spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3319}/${DB_NAME:email_delivery}?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: ${DB_USERNAME:root}
    password: ${DB_ROOT_PASSWORD:${DB_PASSWORD:password}}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000        # 5 min
      max-lifetime: 1800000       # 30 min
      connection-timeout: 30000   # 30 sec
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        generate_statistics: false
  jackson:
    time-zone: UTC
